services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/tmp/data:/data
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  axum:
    build:
      context: ./axum
      target: dev
    volumes:
      - ./axum/target/debug/axum:/usr/local/bin/axum:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      - "AXUM_LISTENING_SOCKET=0.0.0.0:3001"
      - "AWS_ACCESS_KEY_ID=${MINIO_DEV_USER}"
      - "AWS_SECRET_ACCESS_KEY=${MINIO_DEV_PASSWORD}"
      - "AWS_ENDPOINT_URL=http://172.19.0.2:9000"
      - "AWS_REGION=us-east-1"
    command: /usr/local/bin/axum 
    ports:
      - 3001:3001