services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/tmp/data:/data
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  axum:
    build: axum/
    environment:
      - "AXUM_LISTENING_PORT=3001"
      - "MINIO_DEV_USER=${MINIO_DEV_USER}"
      - "MINIO_DEV_PASSWORD=${MINIO_DEV_PASSWORD}"
      - "MINIO_ENDPOINT=http://minio:9000"
    volumes:
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    ports:
      - 3001:3001

volumes:
  cargo-cache:
  target-cache: